Add duplication validation to pre-commit hook

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,9 +1,14 @@
 #!/bin/bash
-# Validate the data files in the same way as it's done on GitHub Actions. The
-# script runs all checks to completion and then exits with a non-zero exit code
-# if any of them failed (as opposed to exiting on the first failing check). This
-# simulates the parallel execution of jobs in GitHub Actions and ensures that
-# all failing checks are seen in a single pass, if there are multiple ones.
+#
+# Validate the data files in the same way as it's done on GitHub Actions.
+#
+# The hook runs all checks to completion even if one of them fails (as opposed
+# to exiting on the first failed check). This mirrors the parallel execution of
+# jobs in GitHub Actions and ensures that all failing checks are seen at once.
+#
+# Each script may have specific dependencies (such as installed packages), which
+# are declared in the main comment of the script. These dependecies must be
+# satisfied for the hook to succeed.
 
 echo "PRE-COMMIT HOOK"
 
@@ -12,6 +17,9 @@ unset failed
 
 echo "==> Running schema validation..."
 scripts/validate-schema.sh >/dev/null && echo OK || failed=1
+
+echo "==> Running duplication validation..."
+scripts/validate-duplicates.sh >/dev/null && echo OK || failed=1
 
 # Abort the commit if any of the checks failed
 [[ -z "$failed" ]] && exit 0 || exit 1
